#!/usr/bin/env python3
"""
Aggregate per-video summary markdown files into a single styled HTML document.

Usage:
  python src/summaries_to_html.py output/youtube/cfoooo8337
  python src/summaries_to_html.py output/youtube/cfoooo8337 --lang en
  python src/summaries_to_html.py output/youtube/cfoooo8337 --lang zh-tw -o channel_book.html
"""

import argparse
import base64
import mimetypes
import re
import sys
from pathlib import Path

import markdown


def _image_to_data_uri(img_path: Path) -> str:
    """Convert a local image file to a base64 data URI for embedding in HTML."""
    mime, _ = mimetypes.guess_type(str(img_path))
    mime = mime or "image/jpeg"
    data = base64.b64encode(img_path.read_bytes()).decode()
    return f"data:{mime};base64,{data}"


def _resolve_images(md_text: str, video_dir: Path) -> str:
    """Replace relative image paths in markdown with base64 data URIs."""

    def _replace(match):
        alt = match.group(1)
        src = match.group(2)
        img_path = video_dir / src
        if img_path.exists():
            data_uri = _image_to_data_uri(img_path)
            return f"![{alt}]({data_uri})"
        return match.group(0)

    return re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", _replace, md_text)


HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{lang_attr}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  @page {{
    size: A4;
    margin: 2cm;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    font-family: "Noto Sans TC", "Microsoft JhengHei", "PingFang TC",
                 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    line-height: 1.7;
    color: #1a1a1a;
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem;
    background: #fff;
  }}
  h1 {{
    font-size: 1.6rem;
    border-bottom: 3px solid #2563eb;
    padding-bottom: 0.4rem;
    margin-top: 3rem;
    color: #1e40af;
    page-break-after: avoid;
  }}
  h2 {{
    font-size: 1.2rem;
    color: #374151;
    margin-top: 1.5rem;
    page-break-after: avoid;
  }}
  h3 {{
    font-size: 1.05rem;
    color: #4b5563;
    page-break-after: avoid;
  }}
  img {{
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    margin: 0.8rem 0;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }}
  a {{
    color: #2563eb;
    text-decoration: none;
  }}
  a:hover {{
    text-decoration: underline;
  }}
  ul, ol {{
    padding-left: 1.5rem;
  }}
  li {{
    margin-bottom: 0.3rem;
  }}
  .toc {{
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 1.5rem 2rem;
    margin-bottom: 2rem;
  }}
  .toc h2 {{
    margin-top: 0;
    color: #1e40af;
  }}
  .toc ol {{
    margin: 0;
  }}
  .toc li {{
    margin-bottom: 0.4rem;
  }}
  .video-section {{
    page-break-before: always;
    border-top: 1px solid #e5e7eb;
    padding-top: 1rem;
  }}
  .video-section:first-of-type {{
    page-break-before: avoid;
    border-top: none;
  }}
  .footer {{
    text-align: center;
    color: #9ca3af;
    font-size: 0.85rem;
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid #e5e7eb;
  }}
</style>
</head>
<body>
<div class="toc">
<h2>{toc_title}</h2>
<ol>
{toc_items}
</ol>
</div>
{sections}
<div class="footer">
  Generated by youtube-utils
</div>
</body>
</html>
"""


def build_html(channel_dir: Path, lang: str) -> str:
    """Collect all summary files and build a single HTML document."""
    suffix = f"summary_{lang}.md"
    video_dirs = sorted(
        [d for d in channel_dir.iterdir() if d.is_dir() and (d / suffix).exists()]
    )

    if not video_dirs:
        print(f"No {suffix} files found in {channel_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(video_dirs)} videos with {suffix}")

    lang_attr = "zh-Hant" if "zh" in lang else "en"
    title = (
        f"{channel_dir.name} — {'影片摘要集' if 'zh' in lang else 'Video Summaries'}"
    )
    toc_title = "目錄" if "zh" in lang else "Table of Contents"

    toc_items = []
    sections = []
    md_ext = markdown.Markdown(extensions=["tables", "fenced_code", "toc"])

    for i, vdir in enumerate(video_dirs, 1):
        md_text = (vdir / suffix).read_text(encoding="utf-8")

        # Extract title from first H1
        first_line = md_text.split("\n")[0]
        video_title = re.sub(r"^#+\s*", "", first_line).strip()
        if not video_title:
            video_title = vdir.name

        anchor = f"video-{i}"
        toc_items.append(f'<li><a href="#{anchor}">{video_title}</a></li>')

        # Embed images as base64
        md_text = _resolve_images(md_text, vdir)

        md_ext.reset()
        html_body = md_ext.convert(md_text)

        sections.append(
            f'<div class="video-section" id="{anchor}">\n{html_body}\n</div>'
        )
        print(f"  [{i}/{len(video_dirs)}] {video_title[:60]}")

    return HTML_TEMPLATE.format(
        lang_attr=lang_attr,
        title=title,
        toc_title=toc_title,
        toc_items="\n".join(toc_items),
        sections="\n".join(sections),
    )


def main():
    parser = argparse.ArgumentParser(
        description="Aggregate video summaries into a single HTML document"
    )
    parser.add_argument(
        "channel_dir", help="Channel output directory (e.g. output/youtube/cfoooo8337)"
    )
    parser.add_argument(
        "--lang",
        default="zh-tw",
        help="Summary language suffix (default: zh-tw). Looks for summary_{lang}.md",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output HTML path (default: {channel_dir}/summaries_{lang}.html)",
    )
    args = parser.parse_args()

    channel_dir = Path(args.channel_dir)
    if not channel_dir.is_dir():
        print(f"Error: {channel_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    html = build_html(channel_dir, args.lang)

    out_path = (
        Path(args.output)
        if args.output
        else channel_dir / f"summaries_{args.lang}.html"
    )
    out_path.write_text(html, encoding="utf-8")
    print(f"\nHTML written to: {out_path} ({out_path.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
